language: node_js

branches:
  only:
    - develop
    - master

node_js:
  - "10"
  - "11"

cache:
  directories:
    - "node_modules"

services:
  - docker

install:
  - npm install
  - npm run build

script:
  - npm run lint
  - npm run test:e2e
